### PR TITLE
feat: add shummg's site

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Supports shummg's script distribution site.

~~This PR depends on shummg/textmodule which is not yet implemented.~~

## How Has This Been Tested?

- Each script on the script distribution site can be successfully installed.
- **"年月日カウンタ" does not work properly. I do not know why.**

## Checklist:

- [ ] ~Updated the modification date in `mod.xml`.~ To prevent conflicts from occurring, it will not update `packages.json` at this time.

### CODE REVIEW

**Comment by mitosagi** [comment]
Rebase and update list.json.

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
shu_game requires rikky_module.

**Comment by mitosagi** [comment]
I have fixed it.

**Review by hal-shu-sato — APPROVED** [review]
I can install the `.lua` library and some scripts including `@年月日カウンタ`.
It looks good.

**Pull request merged**
