### PR TITLE
feat: add seed264's script

### LINKED ISSUE #423: 【パッケージの更新】星野なたね（SEED264）氏のスクリプト
https://github.com/SEED264 こちらを参考に作成しました。
- 互換性のため、`"seed264/opticscompensation"`と`"seed264/opticscompensationold"`がありますが、それぞれお互いにconflictsに設定しています（conflictsが実装されたとき向け）。
- `"seed264/opticscompensationold"`は、isHiddenをtrueに設定しています。
- `"cudart32_75.dll"`のisInstallOnlyをtrueに設定していますが、不要でしたら削除をお願いします。

```json
[
  {
    "id": "seed264/pixelsorter",
    "developer": "星野なたね",
    "name": "PixelSorter_s",
    "downloadURLs": [
      "https://github.com/SEED264/PixelSorter_s/releases"
    ],
    "latestVersion": "1.61",
    "files": [
      { "filename": "script/seed264/PixelSorter_s.anm" },
      { "filename": "script/seed264/PixelSorter_s.dll" }
    ],
    "releases": [
      {
        "version": "1.61",
        "integrity": {
          "archive": "sha384-Cez31FFQ7AV1cu1NkS/XEvrSGBfrXmiczHDIqg2cibd4pzOQGl2bqfiXGb4SKLYV",
          "file": [
            {
              "target": "script/seed264/PixelSorter_s.anm",
              "hash": "sha384-/AsJG+8gPwzgQgjYuvsyYf/WS4VtUgaIwmQ7UjKWPuQyIGNQYqKha6RxkRi1ZBRL"
            },
            {
              "filename": "script/seed264/PixelSorter_s.dll",
              "hash": "sha384-C0lZ6qAPIvpWX0wKM1k+yJN0CaHVA8py0synSFWxSKbku5IwqFzRlyHIBKqYsZuK"
            }
          ]
        }
      },
      {
        "version": "1.61 (Eng)",
        "integrity": {
          "archive": "sha384-7ksGhrwIZk+1iwOoMvAoDZMED5649WLJo/ipSih22GvST3AbEjW67LwCqNKmuJur",
          "file": [
            {
              "target": "script/seed264/PixelSorter_s.anm",
              "hash": "sha384-9QMlucDkR1PTvulhjKU8A246jMmyOKS7dFSnLNRvDpUCKiF1m7zMt6FAGpNmCBE5"
            },
            {
              "filename": "script/seed264/PixelSorter_s.dll",
              "hash": "sha384-qHXfXl4dEjXXmPletwsplAEExYgOY6V35NK7jYpx4jScwrkdihesMj4YgbouAlD/"
            }
          ]
        }
      },
      {
        "version": "1.60",
        "integrity": {
          "archive": "sha384-Cez31FFQ7AV1cu1NkS/XEvrSGBfrXmiczHDIqg2cibd4pzOQGl2bqfiXGb4SKLYV",
          "file": [
            {
              "target": "script/seed264/PixelSorter_s.anm",
              "hash": "sha384-/AsJG+8gPwzgQgjYuvsyYf/WS4VtUgaIwmQ7UjKWPuQyIGNQYqKha6RxkRi1ZBRL"
            },
            {
              "filename": "script/seed264/PixelSorter_s.dll",
              "hash": "sha384-MZ15lOJgR2BZYXzJIYzjZzdY19FUY9s0YuSgRSkXfII6AnUDjedMIUUwxoQPOFOT"
            }
          ]
        }
      }
    ],
    "overview": "高速なPixelSorter",
    "pageURL": "https://github.com/SEED264/PixelSorter_s",
    "description": "Aodaruma氏の「Pixel Sort_A」をDLL化したアニメーション効果です。"
  },
  {
    "id": "seed264/radialwipe",
    "downloadURLs": [
      "https://github.com/SEED264/RadialWipe_s/releases"
    ],
    "name": "RadialWipe_s",
    "developer": "星野なたね",
    "pageURL": "https://twitter.com/seed264/status/1094665960915488768",
    "latestVersion": "1.1",
    "overview": "扇状にクリッピング",
    "description": "扇状にクリッピングを行うアニメーション効果です。",
    "files": [
      { "filename": "script/seed264/RadialBlind_s.anm" },
      { "filename": "script/seed264/RadialWipe_s.dll" },
      { "filename": "script/seed264/RadialWipe_s.anm" }
    ],
    "releases": [
      {
        "version": "1.1",
        "integrity": {
          "archive": "sha384-oHb6mzT3zSE1hIPz76BrQ72X6DqNBYWJYdHhGKEFGV1wRGMgA0X7mPSAcp6WNLD8",
          "file": [
            {
              "target": "script/seed264/RadialBlind_s.anm",
              "hash": "sha384-E4Z4COAx0RsOAMTL1ptbaFxen7PHSazG09r/6wk1zukuWy7gRWqXey47nXBaAWCB"
            },
            {
              "target": "script/seed264/RadialWipe_s.dll",
              "hash": "sha384-O4+ffBa8bBMUun8ArdrfiY5n7ClVsqBMH06Zw0bBClZgU0F4t8USUl0yogfjQAa1"
            },
            {
              "target": "script/seed264/RadialWipe_s.anm",
              "hash": "sha384-LfDVsTsrKbUBJYfYs6bUS2xBXX1tWsxGiHD+kMuFzJBV977URErbjfMPj+WOW/+i"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "seed264/opticscompensation",
    "downloadURLs": [
      "https://github.com/SEED264/OpticsCompensation_s/releases"
    ],
    "name": "OpticsCompensation_s",
    "developer": "星野なたね",
    "pageURL": "https://twitter.com/SEED264/status/1268646448452657152",
    "latestVersion": "1.1",
    "overview": "レンズ補正",
    "conflicts": ["seed264/opticscompensationold"],
    "description": "いわゆるレンズ補正を行うアニメーション効果です。",
    "files": [
      { "filename": "script/seed264/OpticsCompensation_s.anm" },
      { "filename": "script/seed264/OpticsCompensation_s.dll" }
    ],
    "releases": [
      {
        "version": "1.1",
        "integrity": {
          "archive": "sha384-O1em7VMqPZHdcgmpJ739/6agmlRT54GBtqDFf5yKdYhpXEkPutYHaNMlahHm6CC8",
          "file": [
            {
              "target": "script/seed264/OpticsCompensation_s.anm",
              "hash": "sha384-+7hoPsL03ZlRKQM0o9YN1hNV4buZFp4gpGVHxuphJy1xEI49MwRBzFhkpSaAxAwY"
            },
            {
              "target": "script/seed264/OpticsCompensation_s.dll",
              "hash": "sha384-2RSl5iF4kRxQaSGDskSbDpwPy23/+pmmHgEzgfczEA1rT62rYLPZ4jfrOguBHr88"
            }
          ]
        }
      },
      {
        "version": "1.0",
        "integrity": {
          "archive": "sha384-8CPsFz5osMl4KMAi+gPzXsOo88p8XVSxh1nFJTK2TtwN/ORBd48witGYDxJJsQ/b",
          "file": [
            {
              "target": "script/seed264/OpticsCompensation_s.anm",
              "hash": "sha384-+7hoPsL03ZlRKQM0o9YN1hNV4buZFp4gpGVHxuphJy1xEI49MwRBzFhkpSaAxAwY"
            },
            {
              "target": "script/seed264/OpticsCompensation_s.dll",
              "hash": "sha384-RAiMbdouKoje8UMGjmSTMnIeIN4ECQPO0jkqs/WUvHkgrktlnuQN1nNGGEP45AWd"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "seed264/opticscompensationold",
    "downloadURLs": [
      "https://github.com/SEED264/OpticsCompensation_s_Old/releases"
    ],
    "name": "OpticsCompensation_s_Old",
    "developer": "星野なたね",
    "pageURL": "https://github.com/SEED264/OpticsCompensation_s_Old",
    "latestVersion": "1.10",
    "overview": "レンズ補正",
    "description": "いわゆるレンズ補正を行うアニメーション効果です。",
    "conflicts": ["seed264/opticscompensation"],
    "isHidden": true,
    "files": [
      { "filename": "script/seed264/OpticsCompensation_s.anm" },
      { "filename": "script/seed264/OpticsCompensation_s.dll" },
      { "filename": "script/seed264/OpticsCompensation_Direct_s.anm", "isObsolete": true },
      { "filename": "cudart32_75.dll", "isInstallOnly": true }
    ],
    "releases": [
      {
        "version": "1.10",
        "integrity": {
          "archive": "sha384-nXO6/f30lL4T5kFzZrUnh/dSNJ6ZIP+ZEDtaqJYUXINhA0vqNUU6ruNFUfcF3Lrq",
          "file": [
            {
              "target": "script/seed264/OpticsCompensation_s.anm",
              "hash": "sha384-qnUIpCu6HjL8ITlQsFbqldPdLEBY3p6UfgbralnUwyj2m2RAYImbAIfSKMgpfvoG"
            },
            {
              "target": "script/seed264/OpticsCompensation_s.dll",
              "hash": "sha384-nxgGskIZuA3LUlXcSfW0/ZtdOBqWseCJ861rlitVvXSJcpqj1e84X2j3ZRhLshYK"
            },
            {
              "target": "cudart32_75.dll",
              "hash": "sha384-aXRc8QB31EbMf/tUbw4H/ZT4OY8iqQwsa4D9/7qBsBgax0gPZ+siBpMbHS21xyTr"
            }
          ]
        }
      },
      {
        "version": "1.00",
        "integrity": {
          "archive": "sha384-CBvodkdAYexqwogMQnRKyIPG049FMuEsKFrzQFECqPIryYCkRuk7cEwXKVYQvUks",
          "file": [
            {
              "target": "script/seed264/OpticsCompensation_s.anm",
              "hash": "sha384-aFlP2xMAw2OI6NNVmPnz8m0YDLMNC7hcAyFlZJ5wUlUJkRWq1N4kCkCGXIFLmo2P"
            },
            {
              "target": "script/seed264/OpticsCompensation_Direct_s.anm",
              "hash": "sha384-x6VgL94KFJFMVXuPfjxKnlhh83+rOfQum2rI33TZDDAJ0CN0WcG2FyyQiy5Vy3Lm"
            },
            {
              "target": "script/seed264/OpticsCompensation_s.dll",
              "hash": "sha384-KVWo6M49T1s5eVyceP3ZyRD3tcRkCVEvo2pcqZdd18zxH+6FYSer35uRBNczwqB/"
            },
            {
              "target": "cudart32_75.dll",
              "hash": "sha384-aXRc8QB31EbMf/tUbw4H/ZT4OY8iqQwsa4D9/7qBsBgax0gPZ+siBpMbHS21xyTr"
            }
          ]
        }
      }
    ]
  },
  {
    "id": "seed264/directionalblur",
    "downloadURLs": [
      "https://github.com/SEED264/DirectionalBlur_s/releases"
    ],
    "name": "DirectionalBlur_s",
    "developer": "星野なたね",
    "pageURL": "https://github.com/SEED264/DirectionalBlur_s",
    "latestVersion": "1.00",
    "overview": "CUDAを使用した方向ブラー",
    "description": "CUDAを用いて方向ブラーを行うアニメーション効果です。",
    "files": [
      { "filename": "script/seed264/DirectionalBlur_s.anm" },
      { "filename": "script/seed264/DirectionalBlur_Direct_s.anm" },
      { "filename": "script/seed264/DirectionalBlur_s.dll" },
      { "filename": "cudart32_75.dll", "isInstallOnly": true }
    ],
    "releases": [
      {
        "version": "1.00",
        "integrity": {
          "archive": "sha384-nbosVXCgULqAaGYFOBvey0E7dE+nzC8PFrQ89CztuWebjdXfxY7xdEOXbOBE6Zdz",
          "file": [
            {
              "target": "script/seed264/DirectionalBlur_s.anm",
              "hash": "sha384-dm+D28My/BDCPWnUCK+ACNA8yj9H3bFWUGixMgYrsWjUZLK3ypr8npJVkObddk2P"
            },
            {
              "target": "script/seed264/DirectionalBlur_s.dll",
              "hash": "sha384-lkwqZVERvr6BoCD8UGBIPQymn3SHKIpgcPRh+9H8EXSVhZNKCk73ib51FUrw0zpc"
            },
            {
              "target": "script/seed264/DirectionalBlur_Direct_s.anm",
              "hash": "sha384-NrSbC/uqS5biUb09sgTVaLYSaqveRU6c3XZTS1whcZU95xkMG2RIm6nB9nuFFXbr"
            },
            {
              "target": "cudart32_75.dll",
              "hash": "sha384-aXRc8QB31EbMf/tUbw4H/ZT4OY8iqQwsa4D9/7qBsBgax0gPZ+siBpMbHS21xyTr"
            }
          ]
        }
      }
    ]
  }
]
```

### LINKED ISSUE #434: プラグイン追加要望 :OpticsCompensation_s
## パッケージ名
 OpticsCompensation_s

## 概要
俗にいうレンズ補正とやらです

## 説明
樽型と糸巻き型両対応、中心位置移動可能です
OpenCLで実装しているので対応デバイスがない場合は動作しません
Javieの実装のいい感じなやつです

## 開発者
SEED264

## 紹介ページURL
https://twitter.com/SEED264/status/1268646448452657152?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1268646448452657152%7Ctwgr%5E5928bbd656b2d1feda1a5103710baa3bce057f23%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fseguimiii.com%2Faviutl-tech%2Fopticscompensation

## ダウンロードページURL
https://github.com/SEED264/OpticsCompensation_s/releases

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Add script by SEED264. Please check the operation of **DirectionalBlur_s** if possible. It did not work in my environment.
可能であればDirectionalBlur_sの動作確認をお願いします。

## Related Issue

- closes #423 
- closes #434

## How Has This Been Tested?

- Script installs successfully.
- Script runs successfully.
- CUDA did not work in my environment, so `seed264/directionalblur` is untested.

## Checklist:

- [ ] ~~Updated the modification date in `mod.xml`.~~ To avoid conflicts

### CODE REVIEW

**Review by hal-shu-sato — COMMENTED** [review]
I suggest `SEED264` for the developer ID same as the GitHub ID.
What do you think about it?

**Comment by mitosagi** [comment]
Corrected.

**Review by hal-shu-sato — COMMENTED** [review]
How about changing the name of the directory under `scripts`?
It will be shown in AviUtl so I think showing `SEED264` clearly in AviUtl is better.
What do you think about it?

BTW, `SEED264/directionalblur` works in my environment.

**Comment by mitosagi** [comment]
Thank you for checking the package. I have corrected the folder names.

**Review by hal-shu-sato — APPROVED** [review]
Thank you for adding the data!

**Pull request merged**
